- name: Create the Quay target installation directory
  ansible.builtin.file:
    path: "{{ deploy_minimal_quay_install_dir }}"
    state: directory

- name: Create the PostgresQL target installation directory
  ansible.builtin.file:
    path: "{{ deploy_minimal_quay_install_dir }}/postgres-quay"
    state: directory

- name: Set PostgresQL ACLs on {{ deploy_minimal_quay_install_dir }}/postgres-quay
  ansible.posix.acl:
    path: "{{ deploy_minimal_quay_install_dir }}/postgres-quay"
    entity: "26"
    etype: user
    permissions: wx
    state: present

- name: Launching the PostgresQL container
  containers.podman.podman_container:
    name: postgresql-quay
    ports:
      - "5432:5432"
    env:
      POSTGRESQL_USER: "{{ deploy_minimal_quay_psql_user }}"
      POSTGRESQL_PASSWORD: "{{ deploy_minimal_quay_psql_password }}"
      POSTGRESQL_DATABASE: "{{ deploy_minimal_quay_psql_database }}"
      POSTGRESQL_ADMIN_PASSWORD: "{{ deploy_minimal_quay_psql_admin_password }}"
    image: "registry.redhat.io/rhel8/postgresql-13"
    volume: "{{ deploy_minimal_quay_install_dir }}/postgres-quay:/var/lib/pgsql/data:Z"

- name: Ensure the pg_trgm module is installed in PostgresQL
  containers.podman.podman_container_exec:
    name: postgresql-quay
    command: echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d "{{ deploy_minimal_quay_psql_database  }}" -U "{{ deploy_minimal_quay_psql_user }}"

